### ISSUE TITLE
Syntax error on termux

### ISSUE THREAD

**Issue by Sorunlu** [adrijano/Bitcoin-wallet-cracker#32]
Hello!
I just tried to run this program through termux and i got an error. This is the output of the command ("pip3 install -r requirements.txt")
```error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-64y8x61s/hashlib_ebf15824fd1c4af8b711517f5edf5d72/setup.py", line 68
          print "unknown OS, please update setup.py"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
      [end of output```

**Comment by adrijano** [comment]
try again updated requrements.txt
